from selenium.webdriver.common.by import By

class TeacherAssistantLocators():
    TEXT_INTRODUCING_TEACHER_ASSISTANCE = (By.XPATH, "//p[@class='hero-superscript']")
    TEXT_A_FREE_ASSISTANT_FOR_EVERY_TEACHER = (By.XPATH, '//*[@id="w-node-bc8c9369-bc89-c693-ccdd-ec7d8d1bd5d2-a87d25a4"]/h1/strong')
    TEXT_SAVE_TIME_AND_IMPROVE = (By.XPATH, '//*[@id="w-node-bc8c9369-bc89-c693-ccdd-ec7d8d1bd5d2-a87d25a4"]/p')
    BUTTON_TAKE_A_TOUR = (By.XPATH, '//*[@id="w-node-bc8c9369-bc89-c693-ccdd-ec7d8d1bd5d2-a87d25a4"]/div[2]/a[1]')
    LINK_CHOOSE_YOUR_SUBJECT = (By.XPATH, '//*[@id="w-node-bc8c9369-bc89-c693-ccdd-ec7d8d1bd5d2-a87d25a4"]/div[2]/a[3]')
    CHOOSE_YOUR_SUBJECT_POPUP = (By.XPATH, "//div[@class='subjects-modal-white-bg']")
    CHOOSE_YOUR_SUBJECT_POPUP_CLOSE = (By.XPATH, "//div[@class='modal-close-link dxtrack-user-action']")
    CHOOSE_YOUR_SUBJECT_POPUP_TITLE = (By.XPATH, "//div[@class='feature-1-container subjects modal w-container']//div[@class='h3'][normalize-space()='Start Teaching with Your Assistant!']")
    CHOOSE_YOUR_SUBJECT_POPUP_DESC = (By.XPATH, "//div[@class='feature-1-container subjects modal w-container']//div[@class='paragraph'][contains(text(),'Assign concepts from the subjects below to start u')]")
    CHOOSE_YOUR_SUBJECT_POPUP_SCIENCE_TAB = (By.XPATH, "//a[@id='w-tabs-0-data-w-tab-0']//div[contains(text(),'Science')]")
    CHOOSE_YOUR_SUBJECT_POPUP_SCIENCE_TAB_EARTH_SCIENCE = (By.XPATH, "//a[@data-dx-desc='modal-subjects-earth-science']//div[@class='subject-name'][normalize-space()='Earth Science']")
    CHOOSE_YOUR_SUBJECT_POPUP_SCIENCE_TAB_LIFE_SCIENCE = (By.XPATH, "//div[@class='subjects-items-wrapper modal']//div[@class='subject-name'][normalize-space()='Life Science']")
    CHOOSE_YOUR_SUBJECT_POPUP_SCIENCE_PHYSICAL_SCIENCE = (By.XPATH, "//a[@data-dx-desc='modal-subjects-physical-science']//div[@class='subject-name'][normalize-space()='Physical Science']")
    CHOOSE_YOUR_SUBJECT_POPUP_SCIENCE_TAB_BIOLOGY = (By.XPATH, "//a[@data-dx-desc='modal-subjects-biology']//div[@class='subject-name'][normalize-space()='Biology']")
    CHOOSE_YOUR_SUBJECT_POPUP_SCIENCE_TAB_CHEMISTRY = (By.XPATH, "//a[@data-dx-desc='modal-subjects-chemistry']//div[@class='subject-name'][normalize-space()='Chemistry']")
    CHOOSE_YOUR_SUBJECT_POPUP_SCIENCE_TAB_PHYSICS = (By.XPATH, "//a[@data-dx-desc='modal-subjects-physics']//div[@class='subject-name'][normalize-space()='Physics']")
    CHOOSE_YOUR_SUBJECT_POPUP_MATH_TAB = (By.XPATH, "//a[@id='w-tabs-0-data-w-tab-1']//div[contains(text(),'Math')]")
    CHOOSE_YOUR_SUBJECT_POPUP_MATH_TAB_MG6 = (By.XPATH, "//div[@class='subjects-items-wrapper modal']//div[@class='subject-name'][normalize-space()='Math Grade 6']")
    CHOOSE_YOUR_SUBJECT_POPUP_MATH_TAB_MG7 = (By.XPATH, "//div[@class='subjects-items-wrapper modal']//div[@class='subject-name'][normalize-space()='Math Grade 7']")
    CHOOSE_YOUR_SUBJECT_POPUP_MATH_TAB_MG8 = (By.XPATH, "//div[@class='subjects-items-wrapper modal']//div[@class='subject-name'][normalize-space()='Math Grade 8']")
    CHOOSE_YOUR_SUBJECT_POPUP_MATH_TAB_ALGEBRA = (By.XPATH, "//a[@data-dx-desc='modal-subjects-algebra']//div[@class='subject-name'][normalize-space()='Algebra']")
    CHOOSE_YOUR_SUBJECT_POPUP_MATH_TAB_GEOMETRY = (By.XPATH, "//a[@data-dx-desc='modal-subjects-geometry']//div[@class='subject-name'][normalize-space()='Geometry']")
    CHOOSE_YOUR_SUBJECT_POPUP_MATH_TAB_ALGEBRA_II = (By.XPATH, "//a[@data-dx-desc='modal-subjects-algebra-II']//div[@class='subject-name'][normalize-space()='Algebra II']")
    CHOOSE_YOUR_SUBJECT_POPUP_MATH_TAB_PRECALCULUS = (By.XPATH, "//a[@data-dx-desc='modal-subjects-precalculus']//div[@class='subject-name'][normalize-space()='Precalculus']")
    BROWSE_ALL_FLEXBOOKS_IN_CYS_POPUP = (By.XPATH, "//a[@data-dx-desc='modal-subjects-browse-all-fbs']")
    HERO_IMAGE = (By.XPATH, "//div[@class='hero-image-wrap']")
    TEXT_EVERY_TEACHER_DESERVES = (By.XPATH, "//div[@class='h3 about-blurb']")
    TEXT_TEACHERS_ARE_EXPECTED = (By.XPATH, "//div[@class='paragraph about']")
    TEXT_LIKE_ANY_GREAT_ASSISTANT = (By.XPATH, "//div[@class='paragraph about secondary']")
    TEXT_ISLO = (By.XPATH, "//div[@class='feature-1-section tabs dt']//h1[@class='section-title'][normalize-space()='Improve Student Learning Outcomes']")
    TAB_PERFOMANCE_PATTERNS = (By.XPATH, "//div[normalize-space()='Performance Patterns']")
    CLP_TEXT = (By.XPATH, "//div[@class='text-title-icon']//div[@class='text-title purple'][normalize-space()='Class-Level Patterns']")
    CLP_ICON = (By.XPATH, "//div[@id='w-node-fbece8db-cb2b-2f6d-3e8d-22c1580d6366-a87d25a4']//img[@class='tab-icon title']")
    CLP_TITLE = (By.XPATH, "//h1[@class='tab-title-heading'][contains(text(),'See Patterns in Your Students’ Skill Levels')]")
    CLP_DESC = (By.XPATH, "//div[@id='w-node-fbece8db-cb2b-2f6d-3e8d-22c1580d6366-a87d25a4']//p[contains(text(),'The Teacher Assistant shows you how your students’')]")
    CLP_IMAGE = (By.XPATH, "//img[@id='w-node-_5fdb9306-d114-5275-7fc5-425be2b00176-a87d25a4']")
    TAB_CLASS_INSIGHTS = (By.XPATH, "//div[@class='tab-labels'][normalize-space()='Class Insights']")
    TAB_CLASS_INSIGHTS_ICON = (By.XPATH, "//a[@id='w-tabs-1-data-w-tab-1']//img[@class='tab-icon']")
    TCI_ICON = (By.XPATH, "//div[@id='w-node-_8cb98c80-efbb-3919-2bfa-0f7fd17f7ee0-a87d25a4']//img[@class='tab-icon title']")
    TCI_TEXT = (By.XPATH, "//div[@class='text-title-icon']//div[@class='text-title yellow'][normalize-space()='Class Insights']")
    TCI_TITLE = (By.XPATH, "//h1[@class='tab-title-heading'][normalize-space()='Pinpoint Where Your Students Are Struggling']")
    TCI_DESC = (By.XPATH, "//div[@id='w-node-_8cb98c80-efbb-3919-2bfa-0f7fd17f7ee0-a87d25a4']//p[contains(text(),'The Teacher Assistant uncovers your students’ lear')]")
    TCI_IMAGE = (By.XPATH, "//img[@id='w-node-_8cb98c80-efbb-3919-2bfa-0f7fd17f7ee9-a87d25a4']")
    RECOMMENDATIONS_TAB = (By.XPATH, "//div[@class='tab-labels'][normalize-space()='Recommendations']")
    RECOMMENDATIONS_TAB_ICON = (By.XPATH, "//a[@id='w-tabs-1-data-w-tab-2']//img[@class='tab-icon']")
    RECOMMENDATIONS_ICON = (By.XPATH, "//div[@id='w-node-c4ed765b-0762-ba8b-0f42-7150167355b3-a87d25a4']//img[@class='tab-icon title']")
    RECOMMENDATIONS_TEXT = (By.XPATH, "//div[@class='text-title-icon']//div[@class='text-title green'][normalize-space()='Recommendations']")
    RECOMMENDATIONS_TITLE = (By.XPATH, "//div[@id='w-node-c4ed765b-0762-ba8b-0f42-7150167355b3-a87d25a4']//h1[@class='tab-title-heading'][normalize-space()='Get Actionable Recommendations']")
    RECOMMENDATIONS_DESC = (By.XPATH, "//div[@id='w-node-c4ed765b-0762-ba8b-0f42-7150167355b3-a87d25a4']//p[contains(text(),'The Teacher Assistant provides actionable recommen')]")
    RECOMMENDATIONS_IMAGE = (By.XPATH, "//img[@id='w-node-c4ed765b-0762-ba8b-0f42-7150167355bc-a87d25a4']")